### PR TITLE
Fix typo, add badge with a link to Travis

### PR DESCRIPTION
**Pull request by abitrolly**
This helps to see the last version that was deployed

### CODE REVIEW

**Comment by abitrolly** [comment]
@elopio right now that latest version of IPFS is in edge. How to upgrade it to stable?
```
channels:                    
  stable:      v0.4.13 (335) 10MB -
  candidate:   v0.4.13 (335) 10MB -
  beta:        v0.4.13 (335) 10MB -
  edge:        v0.4.14 (583) 11MB -
```

**Comment by come-maiz** [comment]
Hello@abitrolly, I've just pushed 0.4.14 to candidate. Can you help me testing it?

    sudo snap refresh ipfs --candidate

**Review by come-maiz — APPROVED** [review]
Thanks a lot! Merging.

**Comment by abitrolly** [comment]
I don't see where the `ipfs` stores its files. There is no `Datastore.Path` in `show config` as described in the last step of this tutorial

https://flyingzumwalt.gitbooks.io/decentralized-web-primer/install-ipfs/lessons/initialize-repository.html

**Pull request merged**
